package com.ubtech.im.common.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AlphaMessage.proto

public final class AlphaMessage {
  private AlphaMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AlphaMessageResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .AlphaMessageHeaderResponse header = 1;
    /**
     * <code>required .AlphaMessageHeaderResponse header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .AlphaMessageHeaderResponse header = 1;</code>
     */
    AlphaMessageHeader.AlphaMessageHeaderResponse getHeader();
    /**
     * <code>required .AlphaMessageHeaderResponse header = 1;</code>
     */
    AlphaMessageHeader.AlphaMessageHeaderResponseOrBuilder getHeaderOrBuilder();

    // required bytes bodyData = 2;
    /**
     * <code>required bytes bodyData = 2;</code>
     */
    boolean hasBodyData();
    /**
     * <code>required bytes bodyData = 2;</code>
     */
    com.google.protobuf.ByteString getBodyData();
  }
  /**
   * Protobuf type {@code AlphaMessageResponse}
   */
  public static final class AlphaMessageResponse extends
      com.google.protobuf.GeneratedMessage
      implements AlphaMessageResponseOrBuilder {
    // Use AlphaMessageResponse.newBuilder() to construct.
    private AlphaMessageResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AlphaMessageResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AlphaMessageResponse defaultInstance;
    public static AlphaMessageResponse getDefaultInstance() {
      return defaultInstance;
    }

    public AlphaMessageResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }

    @SuppressWarnings("unused")
    private AlphaMessageResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
	int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              AlphaMessageHeader.AlphaMessageHeaderResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(AlphaMessageHeader.AlphaMessageHeaderResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              bodyData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AlphaMessage.internal_static_AlphaMessageResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AlphaMessage.internal_static_AlphaMessageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AlphaMessage.AlphaMessageResponse.class, AlphaMessage.AlphaMessageResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<AlphaMessageResponse> PARSER =
        new com.google.protobuf.AbstractParser<AlphaMessageResponse>() {
      public AlphaMessageResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlphaMessageResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AlphaMessageResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .AlphaMessageHeaderResponse header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private AlphaMessageHeader.AlphaMessageHeaderResponse header_;
    /**
     * <code>required .AlphaMessageHeaderResponse header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .AlphaMessageHeaderResponse header = 1;</code>
     */
    public AlphaMessageHeader.AlphaMessageHeaderResponse getHeader() {
      return header_;
    }
    /**
     * <code>required .AlphaMessageHeaderResponse header = 1;</code>
     */
    public AlphaMessageHeader.AlphaMessageHeaderResponseOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    // required bytes bodyData = 2;
    public static final int BODYDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString bodyData_;
    /**
     * <code>required bytes bodyData = 2;</code>
     */
    public boolean hasBodyData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes bodyData = 2;</code>
     */
    public com.google.protobuf.ByteString getBodyData() {
      return bodyData_;
    }

    private void initFields() {
      header_ = AlphaMessageHeader.AlphaMessageHeaderResponse.getDefaultInstance();
      bodyData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBodyData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, bodyData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, bodyData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static AlphaMessage.AlphaMessageResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlphaMessage.AlphaMessageResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlphaMessage.AlphaMessageResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlphaMessage.AlphaMessageResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlphaMessage.AlphaMessageResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AlphaMessage.AlphaMessageResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static AlphaMessage.AlphaMessageResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static AlphaMessage.AlphaMessageResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static AlphaMessage.AlphaMessageResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AlphaMessage.AlphaMessageResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(AlphaMessage.AlphaMessageResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AlphaMessageResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements AlphaMessage.AlphaMessageResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AlphaMessage.internal_static_AlphaMessageResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AlphaMessage.internal_static_AlphaMessageResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AlphaMessage.AlphaMessageResponse.class, AlphaMessage.AlphaMessageResponse.Builder.class);
      }

      // Construct using AlphaMessage.AlphaMessageResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = AlphaMessageHeader.AlphaMessageHeaderResponse.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        bodyData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AlphaMessage.internal_static_AlphaMessageResponse_descriptor;
      }

      public AlphaMessage.AlphaMessageResponse getDefaultInstanceForType() {
        return AlphaMessage.AlphaMessageResponse.getDefaultInstance();
      }

      public AlphaMessage.AlphaMessageResponse build() {
        AlphaMessage.AlphaMessageResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AlphaMessage.AlphaMessageResponse buildPartial() {
        AlphaMessage.AlphaMessageResponse result = new AlphaMessage.AlphaMessageResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bodyData_ = bodyData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AlphaMessage.AlphaMessageResponse) {
          return mergeFrom((AlphaMessage.AlphaMessageResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AlphaMessage.AlphaMessageResponse other) {
        if (other == AlphaMessage.AlphaMessageResponse.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasBodyData()) {
          setBodyData(other.getBodyData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!hasBodyData()) {
          
          return false;
        }
        if (!getHeader().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AlphaMessage.AlphaMessageResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AlphaMessage.AlphaMessageResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .AlphaMessageHeaderResponse header = 1;
      private AlphaMessageHeader.AlphaMessageHeaderResponse header_ = AlphaMessageHeader.AlphaMessageHeaderResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          AlphaMessageHeader.AlphaMessageHeaderResponse, AlphaMessageHeader.AlphaMessageHeaderResponse.Builder, AlphaMessageHeader.AlphaMessageHeaderResponseOrBuilder> headerBuilder_;
      /**
       * <code>required .AlphaMessageHeaderResponse header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .AlphaMessageHeaderResponse header = 1;</code>
       */
      public AlphaMessageHeader.AlphaMessageHeaderResponse getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .AlphaMessageHeaderResponse header = 1;</code>
       */
      public Builder setHeader(AlphaMessageHeader.AlphaMessageHeaderResponse value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .AlphaMessageHeaderResponse header = 1;</code>
       */
      public Builder setHeader(
          AlphaMessageHeader.AlphaMessageHeaderResponse.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .AlphaMessageHeaderResponse header = 1;</code>
       */
      public Builder mergeHeader(AlphaMessageHeader.AlphaMessageHeaderResponse value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != AlphaMessageHeader.AlphaMessageHeaderResponse.getDefaultInstance()) {
            header_ =
              AlphaMessageHeader.AlphaMessageHeaderResponse.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .AlphaMessageHeaderResponse header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = AlphaMessageHeader.AlphaMessageHeaderResponse.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .AlphaMessageHeaderResponse header = 1;</code>
       */
      public AlphaMessageHeader.AlphaMessageHeaderResponse.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .AlphaMessageHeaderResponse header = 1;</code>
       */
      public AlphaMessageHeader.AlphaMessageHeaderResponseOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>required .AlphaMessageHeaderResponse header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          AlphaMessageHeader.AlphaMessageHeaderResponse, AlphaMessageHeader.AlphaMessageHeaderResponse.Builder, AlphaMessageHeader.AlphaMessageHeaderResponseOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              AlphaMessageHeader.AlphaMessageHeaderResponse, AlphaMessageHeader.AlphaMessageHeaderResponse.Builder, AlphaMessageHeader.AlphaMessageHeaderResponseOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      // required bytes bodyData = 2;
      private com.google.protobuf.ByteString bodyData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes bodyData = 2;</code>
       */
      public boolean hasBodyData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes bodyData = 2;</code>
       */
      public com.google.protobuf.ByteString getBodyData() {
        return bodyData_;
      }
      /**
       * <code>required bytes bodyData = 2;</code>
       */
      public Builder setBodyData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bodyData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes bodyData = 2;</code>
       */
      public Builder clearBodyData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bodyData_ = getDefaultInstance().getBodyData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AlphaMessageResponse)
    }

    static {
      defaultInstance = new AlphaMessageResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AlphaMessageResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_AlphaMessageResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AlphaMessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022AlphaMessage.proto\032\030AlphaMessageHeader" +
      ".proto\"U\n\024AlphaMessageResponse\022+\n\006header" +
      "\030\001 \002(\0132\033.AlphaMessageHeaderResponse\022\020\n\010b" +
      "odyData\030\002 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_AlphaMessageResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_AlphaMessageResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_AlphaMessageResponse_descriptor,
              new java.lang.String[] { "Header", "BodyData", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          AlphaMessageHeader.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
